# Generated by Django 5.1.5 on 2025-01-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name_plural": "Cars"},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name_plural": "Drivers"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"verbose_name_plural": "Manufacturers"},
        ),
    ]
